### ISSUE TITLE
Enter does not confirm selection

### ISSUE THREAD

**Issue by fatualux** [LanceZhu/coc-codegeex#1]
**First of all, thank you for your work, I think it is awesome.**

I have encountered this problem using your plugin:
When I press _Enter_  Vim goes to the next line instead of selecting the highlighted option.

**Steps I followed:**

I installed _coc.nvim_ by adding this to my .vimrc:

`Plug 'neoclide/coc.nvim', {'branch': 'release'}`

Then:
```
:source .vimrc
:PlugInstall
:CocInstall coc-codegeex

```
I did not configure coc-codegeex, it started to work perfecly without any intervention (I had already downloaded my .pt models and used it flawlessly on Code OSS... maybe my API key was already set?)

**What I tried:**

I tried to change the selected option by pressing the UP and DOWN arrow keys, and that worked, but I cannot choose the option with _Enter_ or _Tab_.
Being my Vim compiled with graphical support I also tried to select the options with a touchpad click, but obviously it did not work.

Could you help me to solve this little issue?

Thank you

**OS:**
```
Linux
6.2.8-arch1-1
```

**Vim Editor Version:**
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar 21 2023 20:51:42)
Included patches: 1-1420
Compiled by Arch Linux
```

**Comment by fatualux** [comment]
EDIT: I noticed that Ctrl + n selects the option, I will try to understand why reading my .vimrc

**Comment by LanceZhu** [comment]
remap `Enter` to confirm completion in .vimrc

```
inoremap <expr> <cr> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"
```

see more config: https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#use-cr-to-confirm-completion

**Comment by LanceZhu** [comment]
To check if your API key is configured, use `:CocConfig` to see whether if the `codegeex` key exists.

If you didn't config the API key, the completions may be provided by other plugins of coc.nvim.

**Comment by fatualux** [comment]
Thank you  so much for your support.
Is there a way to use my pretrained models for codegeex just like I do with Code OSS? thanks again

**Comment by LanceZhu** [comment]
It's not supported currently in this extension. If you want do this, you can change the URL and params to your models interference API. 

`code_generate`
https://github.com/LanceZhu/coc-codegeex/blob/054dbc3ccc64fb298195f0906f061d4abdaefbd8/src/utils/getCodeCompletions.ts#L21-L28

`code_translation`
https://github.com/LanceZhu/coc-codegeex/blob/054dbc3ccc64fb298195f0906f061d4abdaefbd8/src/utils/getCodeCompletions.ts#L59-L66

**Comment by fatualux** [comment]
Thanks again, but i cannot find coc-codegeex/src/utils/getCodeCompletions.ts in .config/coc/path/to/codegeex/extension

**Comment by LanceZhu** [comment]
This file `src/utils/getCodeCompletions.ts` is in the source code.

Currently, the `coc-codegeex` extension doesn't expose interface to change the model inference API. If you want change the inference API,  you need change it in the source code.

1. Clone this repo, 

2. Change the source code(update the API),

3. `npm install` `npm run build`,

4. Config vim to use the local extension. 
	
	`set runtimepath^=/path/to/coc-codegeex` in the `.vimrc`. Remeber to disable the previous installed `coc-codegeex` extension by using `:CocList extensions`

In the future, I will try to expose the API (when I have time). If you are interesting in this project, welcome your PR.

**Comment by fatualux** [comment]
Ok, thank you.
You have been very kind and patient :)
